# Generated by Django 4.1.7 on 2023-04-08 14:50

from django.db import migrations, models
import django.db.models.deletion
import rentapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to=rentapp.models.getFileName)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields={
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('Home_image', models.ImageField(blank=True, null=True, upload_to=rentapp.models.getFileName)),
                ('address', models.TextField(max_length=800)),
                ('safety', models.TextField(max_length=600)),
                ('amount', models.IntegerField()),
                ('status', models.BooleanField(default=False, help_text='default,1-Hidden')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentapp.catagory')),
            },
        ),
    ]
