# Generated by Django 4.1.7 on 2023-04-09 08:01

from django.db import migrations, models
import rentapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Home_image',
            new_name='Home_image1',
        ),
        migrations.AddField(
            model_name='product',
            name='Home_image2',
            field=models.ImageField(blank=True, null=True, upload_to=rentapp.models.getFileName),
        ),
        migrations.AddField(
            model_name='product',
            name='Home_image3',
            field=models.ImageField(blank=True, null=True, upload_to=rentapp.models.getFileName),
        ),
        migrations.AddField(
            model_name='product',
            name='Home_image4',
            field=models.ImageField(blank=True, null=True, upload_to=rentapp.models.getFileName),
        ),
    ]
