# Generated by Django 4.1.7 on 2023-04-14 15:32

from django.db import migrations, models
import django.db.models.deletion
import rentapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0002_rename_home_image_product_home_image1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('Home_image1', models.ImageField(blank=True, null=True, upload_to=rentapp.models.getFileName)),
                ('Home_image2', models.ImageField(blank=True, null=True, upload_to=rentapp.models.getFileName)),
                ('Home_image3', models.ImageField(blank=True, null=True, upload_to=rentapp.models.getFileName)),
                ('Home_image4', models.ImageField(blank=True, null=True, upload_to=rentapp.models.getFileName)),
                ('address', models.TextField(max_length=800)),
                ('pin_code', models.IntegerField()),
                ('safety', models.TextField(max_length=600)),
                ('amount', models.IntegerField()),
                ('status', models.BooleanField(default=False, help_text='default,1-Hidden')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to=rentapp.models.getFileName)),
                ('safety', models.TextField(blank=True, max_length=600, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Catagory',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='add_place',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentapp.house'),
        ),
    ]
