# Generated by Django 4.1.7 on 2023-05-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='lat',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='long',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
    ]
