# Generated by Django 4.1.7 on 2023-05-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0002_search_lat_search_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='lat',
            field=models.DecimalField(decimal_places=1, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='long',
            field=models.DecimalField(decimal_places=1, max_digits=30, null=True),
        ),
    ]
